name: Download App Keystore

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: "Select App to Download"
        required: true
        type: choice
        options:
          - abdo
          - o_smart
          - omar

jobs:
  download-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Zip App Folder
        run: |
          APP_NAME="${{ inputs.app_name }}"
          zip -r "${APP_NAME}-keystore.zip" "apps/${APP_NAME}"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "${{ inputs.app_name }}-keystore"
          path: "${{ inputs.app_name }}-keystore.zip"
